version: '3.8'
services:
    server:
        build: .
        ports:
            - '80:3000'
        volumes:
            - ./config:/app/config
            - ./media:/app/media
        environment:
            - LOG_LEVEL=info
